### ISSUE TITLE
Tracking migration to updated metadata schema

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-addons#200]
## Background
Thanks to @chennes we have a really robust way to categorize and systematize addons/macros/preference packs. So this thread will track the progress of getting addon devs to migrate to it. 

* Info about the schema is at: https://wiki.freecad.org/Package_Metadata
* Example of an implemented schema: (see below tracked PRs for some examples)

### Workbenches
- [x] 3DfindIT
- [ ] 3D_Printing_Tools
- [x] A2plus https://github.com/kbwbe/A2plus/issues/449
- [x] AirPlaneDesign
- [ ] animation
- [ ] ArchTextures
- [ ] Assembly2
- [x] Assembly3
- [x] Assembly4 :100:
- [ ] Autoload
- [x] BCFPlugin
- [x] Beltrami :100: https://github.com/Simturb/Beltrami/commits/main/package.xml
- [x] BIM https://github.com/yorikvanhavre/BIM_Workbench/issues/87
- [ ] BIMBots
- [ ] bimtester
- [ ] BOLTSFC
- [ ] CADExchanger
- [ ] cadquery_module
- [ ] Cfd
- [x] CfdOF
- [ ] CommandPanel
- [ ] CubeMenu
- [ ] cura_engine
- [x] CurvedShapes https://github.com/chbergmann/CurvedShapesWorkbench/issues/18
- [x] Curves :100:
- [x] Defeaturing
- [x] Design456 https://github.com/MariwanJ/Design456/blob/main/package.xml
- [x] DesignSPHysics https://github.com/DualSPHysics/DesignSPHysics/issues/106
- [ ] dodo
- [ ] drawing_dimensioning
- [ ] dxf_library
- [x] DynamicData
- [ ] EM
- [ ] ExplodedAssembly
- [x] fasteners
- [x] FCGear https://github.com/looooo/freecad.gears/issues/99
- [x] FEM_FrontISTR
- [ ] flamingo
- [ ] frame
- [x] GDML https://github.com/KeithSloan/GDML/issues/76 
- [ ] Glass
- [ ] icons
- [ ] IconThemes
- [ ] ImportNURBS
- [x] InventorLoader
- [ ] kerkythea
- [x] kicadStepUpMod :100:
- [x] lattice2
- [ ] Launcher
- [ ] LCInterlocking
- [ ] Lithophane
- [ ] MakerWorkbench
- [x] Manipulator
- [ ] Marz https://github.com/mnesarco/MarzWorkbench/issues/15
- [x] MeshRemodel :100:
- [ ] MnesarcoUtils
- [ ] ModernUI
- [ ] MOOC
- [ ] NavigationIndicator
- [ ] nurbs
- [x] OpticsWorkbench
- [ ] ose-piping
- [x] Part-o-magic
- [ ] parts_library
- [ ] pcb
- [ ] persistenttoolbars
- [ ] PieMenu
- [ ] pivy_trackers
- [ ] Plot
- [ ] pluginloader
- [ ] POV-Ray-Rendering
- [ ] Pyramids-and-Polyhedrons
- [ ] pyrate
- [ ] reconstruction
- [x] Reinforcement
- [ ] RemBench
- [x] Render https://github.com/FreeCAD/FreeCAD-render/issues/167
- [ ] Reporting
- [ ] retr3d
- [x] Rocket
- [ ] SelectorToolbar
- [x] sheetmetal https://github.com/shaise/FreeCAD_SheetMetal/commit/d5235fa14097c644d8f77585e14261486264280b
- [x] Ship https://github.com/FreeCAD/freecad.ship/issues/36
- [ ] ShortCuts
- [x] Silk https://github.com/edwardvmills/Silk/issues/24
- [ ] slic3r-tools
- [ ] SlopedPlanesMacro
- [ ] SteelColumn
- [ ] symbols_library
- [ ] TabBar
- [x] ThreadProfile :100:
- [ ] timber
- [ ] ToolbarStyle
- [x] Trails
- [ ] WebTools
- [ ] workfeature
- [ ] workfeature-macro
- [ ] yaml-workspace

**Comment by DeepSOIC** [comment]
> \<date>
>
> REQUIRED
>
> The date of the last update, in the format YYYY-MM-DD or YYYY.MM.DD. 

Am i now supposed to update it upon every commit to my workbench? Because that sounds like a bit of a git merge conflict generator, apart from being an easy-to-forget red-herring...

i'm sorry if it's a stupid question or not the right place to discuss it. I didn't instantly find it at the forum at least.

**Comment by chennes** [comment]
The idea isn't to update it every commit, but every time you change the version number.

**Comment by DeepSOIC** [comment]
@chennes oh, wait, do i have to change the version number for every commit too?

**Comment by chennes** [comment]
You can do whatever you want with the version number, I don't think we want to get in the business of telling developers how they have to do that. I'm working on some new code now to better handle displaying the last commit date, and that will also enable better update handling for both git and non-git users. So don't worry too much about it right now.

**Comment by davesrocketshop** [comment]
Rocket workbench updated

**Comment by luzpaz** [comment]
@chennes should we fork @triplus's repos to the FreeCAD organization and maintain them ?

**Comment by chennes** [comment]
It would probably be better if there were a specific human being who was interested in maintaining some or all of them. I haven't seen triplus around in a year or two, but I don't know the story there.

**Comment by chennes** [comment]
On a different note, Pyrate has the metadata file in their official repo on Debian Salsa. I have not ever tried to have two different submodules with the same name, though, so I don't know how to handle that. 0.19.3 supports Salsa now, but nothing before that does. I don't know when we want to pull the trigger on making that shift.

**Comment by luzpaz** [comment]
I think I may be able to find some volunteers. I'll start a tracking ticket.

**Comment by luzpaz** [comment]
> I have not ever tried to have two different submodules with the same name, though, so I don't know how to handle that.  

Oy vey, here comes the complexity.

**Comment by luzpaz** [comment]
I guess we should close this ticket?
